services:
  vrompt-web:
    environment:
      WATCHPACK_POLLING: 'true'
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: '1000'
      NEXT_DIST_DIR: .next-docker
    volumes:
      - vrompt-web-next:/workspace/apps/web/.next-docker

volumes:
  vrompt-web-next:
